defaults: &defaults
 
:development:
  :couchdb:
    :url: http://couch.dev.worddit.org/worddit_dev
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://couch.dev.worddit.org/worddit_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://couch.dev.worddit.org/worddit
    <<: *defaults